### ISSUE TITLE
Singletons leak objects

### ISSUE THREAD

**Issue by TJHeuvel** [FronkonGames/GameWork-Foundation#1]
https://github.com/FronkonGames/GameWork-Foundation/blob/main/Runtime/Patterns/Creational/Singleton/MonoBehaviourSingleton.cs

The static instance is set, but never unset. This means if we have a singleton in one scene, and load the next, the previous singleton is never unloaded properly, eventhough the GameObject is gone. You can confirm this in the Memory Profiler. 

Its imperative the static instance is set to `null` when the Gameobject is destroyed.

**Comment by TJHeuvel** [comment]
https://github.com/FronkonGames/GameWork-Foundation/blob/main/Runtime/Patterns/Creational/Singleton/MonoBehaviourSingleton.cs#L36

Personally i'd also avoid the FindObjectOfType, instead assign in an Awake. This for performance reasons.

**Comment by FronkonGames** [comment]
I used OnDestoy to free the static instance.  I have also added a persistent version between scenes (PersistentMonoBehaviourSingleton).

For now I will leave FindObjectOfType in the lazy creation. I have added a performance warning ;)

Thanks for creating the issue TJHeuvel.
