### ISSUE TITLE
BaseMonoBehaviour missing

### ISSUE THREAD

**Issue by gadget114514** [FronkonGames/GameWork-Foundation#2]
BaseMonoBehaviour missing

**Comment by FronkonGames** [comment]
As stated in the [Changelog](https://github.com/FronkonGames/GameWork-Foundation/blob/main/CHANGELOG.md) of version 0.0.13:

- BaseMonoBehaviour renamed to CachedMonoBehaviour.

I am sorry to make a change that "breaks" the API (it is still in version 0.0.X) but it seems to me a name that better reflects its usability.
